-- SQL dump generated by export_db_sql.js
BEGIN;

-- CREATE TABLE usuarios
CREATE TABLE IF NOT EXISTS "public"."usuarios" (
  "id" int4 DEFAULT nextval('usuarios_id_seq'::regclass) NOT NULL,
  "rut" varchar(12) NOT NULL,
  "password" text NOT NULL,
  "rol" varchar(20) NOT NULL,
  "token" text,
  "activo" bool DEFAULT true,
  "nombres" text,
  "apellidos" text,
  "created_at" timestamp DEFAULT now(),
  "email" varchar(255),
  CONSTRAINT "usuarios_email_key" UNIQUE (email),
  CONSTRAINT "usuarios_pkey" PRIMARY KEY (id),
  CONSTRAINT "usuarios_rol_check" CHECK (((rol)::text = ANY ((ARRAY['administrador'::character varying, 'supervisor'::character varying, 'operador'::character varying, 'superusuario'::character varying])::text[])))
);


-- Sequences (will be created if referenced)
CREATE SEQUENCE IF NOT EXISTS "usuarios_id_seq";
ALTER SEQUENCE "usuarios_id_seq" OWNED BY "public"."usuarios"."id";

-- Inserts

-- Data for table usuarios

-- Foreign key constraints

-- Set sequence values
SELECT setval('"usuarios_id_seq"', 0, true);

COMMIT;
